version: '3'
services:
  zabbix-mysql:
    image: mysql:5.7
    hostname: zabbix-mysql
    restart: always
    ports:
      - "3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_bin
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 123456

  zabbix-java-gateway:
    hostname: zabbix-java-gateway
    image: zabbix/zabbix-java-gateway:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime

  zabbix-server:
    depends_on:
      - zabbix-mysql
    hostname: zabbix-server
    restart: always
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 123456
      ZBX_JAVAGATEWAY: zabbix-java-gateway

  zabbix-nginx:
    depends_on:
      - zabbix-server
    hostname: zabbix-nginx
    restart: always
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - "80:8080"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: 123456
      ZBX_SERVER_HOST: zabbix-server-mysql
