version: "3.3"
services:
 postgres:
  image: postgres:12-alpine
  container_name: postgresql
  restart: always
  environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
  ports:
    - 5432:5432
  volumes:
    - /root/PostgreSQL/data:/var/lib/postgresql/data

#docker exec -it postgresql bash
#psql -U root -W
#123456
