prometheus:
  image: prom/prometheus:latest
  restart: always
  container_name: prometheus
  hostname: prometheus
  environment:
  - TZ=Asia/Shanghai
  ports:
  - 9090:9090
  command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    - '--storage.tsdb.retention.time=7d'
    - '--web.external-url=prometheus'
  volumes:
  - /data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  - /opt/promdata:/prometheus
grafana:
  image: grafana/grafana:latest
  restart: always
  container_name: grafana
  hostname: grafana
  environment:
  - TZ=Asia/Shanghai
  volumes:
  - /data/grafana:/var/lib/grafana
  ports:
  - 3000:3000
